bundler_args: --without benchmark:development
script: script/cibuild
cache: bundler
language: ruby

rvm:
  - &ruby1 2.7.1
  - &ruby2 2.5.8

env:
  matrix:
    - TEST_SUITE=test

notifications:
  email: false

before_install:
  - gem update --system --no-document
  - gem install bundler --no-document
