bundler_args: --without benchmark:development
script: script/cibuild
cache: bundler
language: ruby

matrix:
  include:
    - rvm: 2.7.0
      env: TEST_SUITE=profile-docs
      name: "Profile Docs"
    - rvm: 2.5.7
      env: TEST_SUITE=memprof
      name: "Profile Memory Allocation"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false

before_install:
  - gem update --system --no-document
  - gem install bundler --no-document
