bundler_args: --without benchmark:development
script: bundle exec ruby script/rubyprof
cache: bundler
language: ruby

rvm:
  - 2.7.0
  - 2.6.5
  - 2.5.7
  - 2.4.9

notifications:
  email: false

before_install:
  - gem update --system --no-document
  - gem install bundler --no-document
