bundler_args: --without benchmark:development
script: script/cibuild
cache: bundler
language: ruby

rvm:
  - 2.6

matrix:
  include:
    - env: TEST_SUITE=profile-docs
      name: "Profile Docs"
    - env: TEST_SUITE=memprof
      name: "Profile Memory Allocation"

env:
  matrix:
    - TEST_SUITE=test

notifications:
  email: false

before_install:
  - gem update --system --no-document
  - gem install bundler --no-document
