bundler_args: --without benchmark:development
script: script/cibuild
cache: bundler
language: ruby

rvm:
  - 2.7.1

env:
  global:
    - TEST_SUITE=memprof
  jobs:
    - BUILD_PHASES="reset"
    - BUILD_PHASES="reset,read"
    - BUILD_PHASES="reset,read,generate"
    - BUILD_PHASES="reset,read,generate,render"
    - BUILD_PHASES="reset,read,generate,render,cleanup"
    - BUILD_PHASES="reset,read,generate,render,cleanup,write"

notifications:
  email: false

before_install:
  - gem update --system --no-document
  - gem install bundler --no-document
