bundler_args: --without benchmark:development
script: script/cucumber
cache: bundler
language: ruby
sudo: false

rvm:
  - &ruby1 2.6.0
  - &ruby2 2.5.3
  - &ruby3 2.4.5
  - &ruby4 2.3.8

notifications:
  email: false

before_install:
  - gem update --system
  - gem install bundler
