bundler_args: --without benchmark:development
script: script/cibuild
cache: bundler
language: ruby

rvm:
  - &ruby2 2.5.8

matrix:
  include:
    - rvm: *ruby2
      env: TEST_SUITE=profile-docs
      name: "Profile Docs"
    - rvm: *ruby2
      env: TEST_SUITE=memprof
      name: "Profile Memory Allocation"

notifications:
  email: false

before_install:
  - gem update --system --no-document
  - gem install bundler --no-document
