bundler_args: --without benchmark:development
script: script/cibuild
cache: bundler
language: ruby
rvm: 2.7.1
env:
  matrix:
    - TEST_SUITE=stackprof
notifications:
  email: false
before_install:
  - gem update --system --no-document
  - gem install bundler --no-document
