bundler_args: --without benchmark:development
script: bundle exec ruby script/rubyprof
cache: bundler
language: ruby

rvm:
  - 2.7
  - 2.6
  - 2.5
  - 2.4

notifications:
  email: false

before_install:
  - gem update --system --no-document
  - gem install bundler --no-document
