script: bundle exec jekyll build --verbose --source docs --destination docs/_site
cache: bundler
language: ruby
sudo: false

rvm:
  - &ruby1 2.5.1
  - &ruby2 2.4.4
  - &ruby3 2.3.7

before_install:
  - gem update --system
  - gem install bundler
