bundler_args: --without development
script: benchmark/parse-include-tag-params.rb
cache: bundler
language: ruby

rvm: 2.4

matrix:
  include:
    - env: BENCHMARK=true
      name: "Benchmark"

notifications:
  email: false

before_install:
  - gem update --system --no-document
  - gem install bundler --no-document
