bundler_args: --without benchmark:development
script: script/cibuild
cache: bundler
language: ruby

matrix:
  include:
    - rvm: 2.7.0
      env: TEST_SUITE=profile-docs
      name: "Profile Docs"
    - rvm: 2.5.7
      env: TEST_SUITE=memprof
      name: "Profile Memory Allocation"

notifications:
  email: false

before_install:
  - gem update --system --no-document
  - gem install bundler --no-document
