version: "{build}"

clone_depth: 5

build: off

environment:
  BUNDLE_WITHOUT: "benchmark:development"
  RUBY_FOLDER_VER: "27"
  matrix:
    - TEST_SUITE: "test"
    - TEST_SUITE: "default-site"
    - TEST_SUITE: "profile-docs"
    - TEST_SUITE: "memprof"
    - TEST_SUITE: "cucumber"

install:
  - SET PATH=C:\Ruby%RUBY_FOLDER_VER%-x64\bin;%PATH%
  - bundle install --retry 5 --jobs=%NUMBER_OF_PROCESSORS% --clean --path vendor\bundle

test_script:
  - ruby --version
  - gem --version
  - bundler --version
  - bash ./script/cibuild

cache:
  # If one of the files after the right arrow changes, cache will be invalidated
  - 'vendor\bundle -> appveyor.yml,Gemfile,jekyll.gemspec'
