# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

# trigger:
# - master

jobs:
- job: Test
  variables:
    TEST_SUITE: test
  strategy:
    matrix:
      Ruby24:
        ruby_version: '2.4.3'
      Ruby25:
        ruby_version: '2.5.0'

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: $(ruby_version)

  - bash: |
      gem install bundler
      bundle install --retry=3 --jobs=4

    displayName: 'bundle install'

  - bash: 'script/fmt'
    displayName: 'Build script'
