jobs:
- job: suite
  variables:
    CI: true
    ruby_version: '2.5.0'
  strategy:
    matrix:
      Cucumber:
        TEST_SUITE: cucumber
      RuboCop:
        TEST_SUITE: fmt
      Default_Site:
        TEST_SUITE: default-site
      Profile_Docs:
        TEST_SUITE: profile-docs
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: $(ruby_version)

  - bash: |
      gem update --system
      gem install bundler
      bundle install --retry=3 --jobs=4

    displayName: install

  - bash: script/cibuild
    displayName: build

