parameters:
  name: ''
  suite: ''

jobs:
- job: ${{ parameters.name }}
  variables:
    TEST_SUITE: ${{ parameters.suite }}
  strategy:
    matrix:
      Ruby24:
        ruby_version: '2.4.3'
      Ruby25:
        ruby_version: '2.5.0'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: $(ruby_version)

  - bash: |
      gem update --system
      gem install bundler
      bundle install --retry=3 --jobs=4

    displayName: install

  - bash: script/cibuild
    displayName: build

