#!/usr/bin/env ruby

require "memory_profiler"
require File.expand_path("../lib/jekyll", __dir__)

report = MemoryProfiler.report do
  Jekyll::Commands::Build.process(
    "source"      => File.expand_path("../docs", __dir__),
    "destination" => File.expand_path("../docs/_site", __dir__)
  )
end

report.pretty_print
