#!/usr/bin/env ruby

require "bundler/setup"
require "json"
require "stackprof"
require File.expand_path("../lib/jekyll", __dir__)

FileUtils.mkdir_p File.expand_path("../tmp", __dir__)

MODE = ARGV.first || "cpu"
PROF_OUTPUT_FILE = File.expand_path("../tmp/stackprof-#{MODE}-#{Time.now.strftime("%Y%m%d%H%M")}.dump", __dir__)

puts "Stackprof Mode: #{MODE}"

unless File.exist?(PROF_OUTPUT_FILE)
  StackProf.run(
    mode: MODE.to_sym,
    interval: 100,
    raw: true,
    out: PROF_OUTPUT_FILE
  ) do
    puts "GC Stats:", JSON.pretty_generate(GC.stat)
    GC.disable

    Jekyll::Commands::Build.process({
      'source'      => File.expand_path("../docs", __dir__),
      "destination" => File.expand_path("../docs/_site", __dir__),
    })

    puts 'GC Stats:'
    GC.start(full_mark: true, immediate_sweep: false)
    puts JSON.pretty_generate(GC.stat)
  end
end

options = {
  sort: true,
  limit: 50,
  format: :text,
}

# You can also do other things. Examples:
# https://github.com/tmm1/stackprof/blob/master/bin/stackprof
dump_data = IO.binread(PROF_OUTPUT_FILE)
report = StackProf::Report.new(Marshal.load(dump_data))
report.print_text(
  options[:sort],
  options[:limit],
  options[:select_files],
  options[:reject_files],
  options[:select_names],
  options[:reject_names]
)

puts "\n\n"
puts JSON.pretty_generate(Marshal.load(dump_data))
