#!/usr/bin/env ruby

require "bundler/setup"
require "json"
require "stackprof"
require File.expand_path("../lib/jekyll", __dir__)

MODE = ARGV.first || "cpu"
PROF_OUTPUT_FILE = File.expand_path("../tmp/stackprof-#{MODE}.dump", __dir__)

puts "Stackprof Mode: #{MODE}"

StackProf.run(
  mode: MODE.to_sym,
  interval: 1000,
  out: PROF_OUTPUT_FILE
) do
  Jekyll::Commands::Build.process({
    'source'      => 'docs',
    'destination' => 'docs/_site'
  })
end

StackProf::Report.new(Marshal.load(IO.binread(PROF_OUTPUT_FILE))).print_method('Jekyll::Emoji.emojify')
puts "Results stored in #{PROF_OUTPUT_FILE}"
