name: Micro Benchmark Runs

on:
  push:
  pull_request:

jobs:
  benchmark:
    name: "Micro Benchmark Run (Ruby ${{ matrix.ruby_version }})"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        ruby_version:
          - "2.5"
          - "2.7"
          - "3.0"
    env:
      BENCHMARK: true
    steps:
    - name: Checkout Jekyll
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    - name: Run Benchmark
      run: bundle exec ruby benchmark/include_tag.rb
