name: Continuous Integration

on:
  push:

jobs:
  ci:
    name: "Run Tests (Ruby ${{ matrix.ruby_version }} on ${{ matrix.os.label }})"
    runs-on: ${{ matrix.os.image }}
    strategy:
      fail-fast: false
      matrix:
        ruby_version: [ "2.7", "3.3" ]
        os:
          - label: Linux
            image: "ubuntu-latest"
          - label: Windows
            image: "windows-latest"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: "Set up Ruby ${{ matrix.ruby_version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Run tests without quoting
        run: |
          bundle exec jekyll foo --ignore docs/
          bundle exec jekyll foo --ignore docs/*
          bundle exec jekyll foo --ignore docs/**
          bundle exec jekyll foo --ignore docs/_data/**
      - name: Run tests with quoting
        run: |
          bundle exec jekyll foo --ignore "docs/"
          bundle exec jekyll foo --ignore "docs/*"
          bundle exec jekyll foo --ignore "docs/**"
          bundle exec jekyll foo --ignore "docs/_data/**"
