name: Diff Jekyll Builds

on: workflow_dispatch

jobs:
  diff_jekyll_builds:
    name: Diff Jekyll Builds
    runs-on: 'ubuntu-latest'
    env:
      BUNDLE_GEMFILE: 'sandbox/Gemfile'
      BUNDLE_PATH: 'vendor/bundle'
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
    steps:
    - name: Checkout Jekyll master
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        path: master
    - name: Checkout Jekyll ref
      uses: actions/checkout@v2
      with:
        fetch-depth: 5
        path: sandbox
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: 'Build Jekyll Docs @ master'
      run: |
        bundle install
        bundle exec jekyll build -s master/docs -d master/docs/_site --trace
    - name: 'Build Jekyll Docs @ ref'
      run: |
        bundle install
        bundle exec jekyll build -s sandbox/docs -d sandbox/docs/_site --trace
    - name: Diff two dest dirs
      run: bash sandbox/.github/workflows/actions/diff-builds master/docs/_site sandbox/docs/_site
