name: Diff Jekyll Builds

on:
  push:

jobs:
  diff_jekyll_builds:
    name: Diff Jekyll Builds
    runs-on: 'ubuntu-latest'
    steps:
      - uses: ashmaroli/diff-jekyll-builds@master
        with:
          base_src: docs
          base_dest: docs/_site
          subject_src: docs
          subject_dest: docs/_site
