name: Build and deploy Jekyll documentation site

on:
  push:

jobs:
  deploy_docs:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        include:
          - label: Ruby 2.7
            ruby_version: "2.7"
          - label: Ruby 3.0
            ruby_version: "3.0"
          - label: Ruby 3.1.2
            ruby_version: "3.1.2"
          - label: Ruby 3.2
            ruby_version: "3.2"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: "Set up ${{ matrix.label }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - run: bundle exec ruby -e "puts JSON.pretty_generate(Hash(ENV))"
