name: Build and deploy Jekyll documentation site

on:
  push:

jobs:
  deploy_docs:
    runs-on: "ubuntu-latest"
    steps:
      - name: Build and deploy docs site
        uses: ashmaroli/deploy-jekyll-build@ruby-ver
        with:
          src_dir: docs
          cache_bundle: true
          build_opts: |
            verbose: true
      - run: ruby -e "puts ENV"
