name: RbSpy

on:
  push:

jobs:
  rbspy:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.3"
          bundler: "2.2.31"
          bundler-cache: true
      - name: Install rbspy
        run: |
          wget https://github.com/rbspy/rbspy/releases/download/v0.8.1/rbspy-x86_64-unknown-linux-gnu.tar.gz
          sudo tar -xf rbspy-x86_64-unknown-linux-gnu.tar.gz -C /usr/local/bin
          sudo mv /usr/local/bin/rbspy-x86_64-unknown-linux-gnu /usr/local/bin/rbspy
          sudo chmod +x /usr/local/bin/rbspy
      - name: Record build profile
        run: |
          rbspy record --raw-file raw.gz --file flamegraph.svg --rate 50 --silent -- \
            bundle exec jekyll build -s docs -d docs/_site --disable-disk-cache
      - name: Print report
        run: |
          rbspy report -f summary_by_line -i raw.gz -o summary.txt
          bundle exec ruby .github/workflows/actions/rbspy_summary.rb summary.txt
