name: RbSpy

on:
  push:

jobs:
  rbspy:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ubuntu-latest-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ubuntu-latest-gems-
      - name: Install gemset
        run: |
          gem install bundler --version 2.2.31
          bundle install
      - name: Install rbspy
        run: |
          wget https://github.com/rbspy/rbspy/releases/download/v0.8.1/rbspy-x86_64-unknown-linux-gnu.tar.gz
          sudo tar -xf rbspy-x86_64-unknown-linux-gnu.tar.gz -C /usr/local/bin
          sudo mv /usr/local/bin/rbspy-x86_64-unknown-linux-gnu /usr/local/bin/rbspy
          sudo chmod +x /usr/local/bin/rbspy
      - run: rbspy record -- jekyll help
