name: Third-Party Repository Profiling

on:
  push:
  pull_request:
    branches:
      - master
jobs:
  build_n_profile:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - "2.7"
          - "jruby-9.2.14.0"
    steps:
    - name: Checkout Jekyll
      uses: actions/checkout@v2
      with:
        fetch-depth: 5
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    - name: Run Jekyll Build 3 times
      run: |
        bundle exec jekyll build -s docs -d docs/_site --trace
        bundle exec jekyll build -s docs -d docs/_site --trace
        bundle exec jekyll build -s docs -d docs/_site --trace
    - name: Memory Analysis of Jekyll Build
      run: bundle exec ruby .github/workflows/actions/memprof.rb docs
