name: Third Party Repository

on: [push]
jobs:
  third_party:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout Jekyll
      uses: actions/checkout@v2
      with:
        fetch-depth: 5
        path: jekyll
    - name: Checkout Third Party Repository
      uses: actions/checkout@v2
      with:
        repository: tomjoht/tomjoht.github.io
        path: sandbox
    - name: Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: sandbox/vendor/bundle
        key: ubuntu-latest-gems-${{ hashFiles('sandbox/Gemfile') }}
        restore-keys: |
          ubuntu-latest-gems-
    - name: Set up dependencies
      run: |
        gem update --system --no-document
        gem update bundler --no-document
        ruby jekyll/.github/workflows/actions/munge_sandbox_gemfile.rb
        bundle config gemfile sandbox/Gemfile
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run Jekyll Build
      run: bundle exec jekyll build -s sandbox -d sandbox/_site --verbose --trace
